export const clients =  [
  {
    id: 3,
    name: "Ana Torres",
    role: "Cliente",
    email: "ana@technova.com",
    status: "inactivo",
    createdAt: "2023-01-15",
  },
  {
    id: 5,
    name: "Marta López",
    role: "Cliente",
    email: "marta@fintrust.es",
    status: "inactivo",
    createdAt: "2023-01-20",
  },
  {
    id: 8,
    name: "Luis Romero",
    role: "Cliente",
    email: "luis@databank.com",
    status: "inactivo",
    createdAt: "2023-01-28",
  },
  {
    id: 9,
    name: "Carmen Díaz",
    role: "Cliente",
    email: "carmen@shopline.com",
    status: "inactivo",
    createdAt: "2023-02-01",
  },
  {
    id: 12,
    name: "Hugo Sánchez",
    role: "Cliente",
    email: "hugo@privacycorp.com",
    status: "inactivo",
    createdAt: "2023-02-07",
  },
  {
    id: 14,
    name: "David Gómez",
    role: "Cliente",
    email: "david@cloudify.io",
    status: "inactivo",
    createdAt: "2023-02-12",
  },
  {
    id: 16,
    name: "Mario Torres",
    role: "Cliente",
    email: "mario@educloud.net",
    status: "inactivo",
    createdAt: "2023-02-16",
  },
  {
    id: 18,
    name: "Alberto Vega",
    role: "Cliente",
    email: "alberto@alphabank.es",
    status: "inactivo",
    createdAt: "2023-02-20",
  },
  {
    id: 20,
    name: "Javier Molina",
    role: "Cliente",
    email: "javier@smartworld.io",
    status: "inactivo",
    createdAt: "2023-02-24",
  },
  {
    id: 22,
    name: "Andrés León",
    role: "Cliente",
    email: "andres@streamnet.es",
    status: "inactivo",
    createdAt: "2023-02-28",
  },
  {
    id: 25,
    name: "Patricia Ramos",
    role: "Cliente",
    email: "patricia@infosecgroup.com",
    status: "inactivo",
    createdAt: "2023-03-06",
  },
];